<section id="link2">
	<div class="section_inner">
		<div class="block first">
			<h5>
				<img class="image" src="<?php echo $_SESSION["rootDir"] ?>images/reserve_icon.png" />
				来店予約受け付け
			</h5>
			<img class="image" src="<?php echo $_SESSION["rootDir"] ?>images/reserve.jpg" />
			<div>
				<p>
					WEBからご来店予約された方にQUOカード500円分をもれなくプレゼント！
				</p>
				<a href="<?php echo $_SESSION["rootDir"] ?>contact.php?kbn=1"><img class="go" src="<?php echo $_SESSION["rootDir"] ?>images/go.png" /></a>
			</div>
		</div>
		<div class="block">
			<h5>
				<img class="image" src="<?php echo $_SESSION["rootDir"] ?>images/estimate_icon.png" />
				無料相談お見積り
			</h5>
			<img class="image" src="<?php echo $_SESSION["rootDir"] ?>images/estimate.jpg" />
			<div>
				<p>
					費用・プランのご相談・お見積りが無料です！お気軽にご連絡ください。
				</p>
				<a href="<?php echo $_SESSION["rootDir"] ?>contact.php?kbn=2"><img class="go" src="<?php echo $_SESSION["rootDir"] ?>images/go.png" /></a>
			</div>
		</div>
		<div class="block">
			<h5>
				<img class="image" src="<?php echo $_SESSION["rootDir"] ?>images/catalog_icon.png" />
				最新チラシ
			</h5>
			<img class="image" src="<?php echo $_SESSION["rootDir"] ?>images/chirashi_2.jpg" />
			<div>
				<p>
					最新のチラシをいつでもパソコン・スマホからチェック！
				</p>
				<a href="<?php echo $_SESSION["rootDir"] ?>news/archives/1339"><img class="go" src="<?php echo $_SESSION["rootDir"] ?>images/go.png" /></a>
			</div>
		</div>
	</div>
	<div class="clear"></div>
</section>

<section id="tel2">
	<div class="section_inner">
		<div class="tel2">
			<img src="<?php echo $_SESSION["rootDir"] ?>images/tel2.png" />
		</div>
		<img class="tel3" src="<?php echo $_SESSION["rootDir"] ?>images/tel3.png" />
	</div>
</section>
